# Generated by Django 4.2 on 2023-04-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default=987654321, max_length=100),
            preserve_default=False,
        ),
    ]
