# Generated by Django 4.2 on 2023-04-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_treatment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
