# Generated by Django 4.2 on 2023-05-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_treatment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treatment',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
